#!/bin/sh
DIR=`dirname $0`

usage() {
  echo "usage: $0 <Module 1> [<Module 2> <Module N>]"
  echo ""
  echo "Available Modules"
  for i in `ls -1 modules`; do
    echo "- $i"
  done
}

if [ $# -eq 0 ]; then
  usage
  exit 1
fi

rm -rf $DIR/build/modules
mkdir -p $DIR/build/modules

while [ "$1" != "" ]; do
  if [ -d "modules/$1" ]; then
    if [ -d "modules/$1/manifests" ]; then
      echo "adding - $1"
      cp -r modules/$1 $DIR/build/modules/
    else
      for i in `ls modules/$1`; do
        if [ -d "modules/$1/$i/manifests" ]; then
          echo "adding - $1/$i"
          cp -r modules/$1/$i $DIR/build/modules/
        fi
      done
    fi
  fi
  shift
done

cd $DIR/build && tar cfz modules.tar.gz modules
if [ $? == 0 ]; then
  echo "completed..."
else
  echo "failed..."
fi
